mod bridge;
mod service;
mod systems;

use std::collections::BTreeMap;
use std::sync::{Arc, Mutex, RwLock};

use bevy::prelude::*;
use tokio::sync::mpsc;

pub use bridge::GrpcControllableJoint;

use bridge::{GrpcBridge, SharedBridgeState};
use service::JointControlService;
use systems::{apply_grpc_commands, publish_joint_states};

/// The proto-generated types are included here so all submodules can use them via `super::proto::*`.
pub mod proto {
    tonic::include_proto!("digital_twin");

    /// File descriptor set for gRPC reflection, generated by tonic-build.
    pub const FILE_DESCRIPTOR_SET: &[u8] =
        tonic::include_file_descriptor_set!("digital_twin_descriptor");
}

use proto::joint_control_server::JointControlServer;

/// A Bevy plugin that starts a gRPC server on a background thread, exposing
/// joint control and state reading for the digital twin simulation.
pub struct GrpcPlugin {
    /// The address to bind the gRPC server to, e.g. `"0.0.0.0:50051"`.
    pub addr: String,
}

impl Plugin for GrpcPlugin {
    fn build(&self, app: &mut App) {
        let (cmd_tx, cmd_rx) = mpsc::channel(256);

        let shared_state = Arc::new(SharedBridgeState {
            joints: RwLock::new(BTreeMap::new()),
            command_tx: cmd_tx,
            command_rx: Mutex::new(cmd_rx),
        });

        app.insert_resource(GrpcBridge {
            shared: shared_state.clone(),
        });

        let addr = self.addr.clone();
        let state_for_server = shared_state.clone();

        std::thread::spawn(move || {
            let rt = tokio::runtime::Builder::new_multi_thread()
                .worker_threads(2)
                .enable_all()
                .build()
                .expect("Failed to create Tokio runtime for gRPC server");

            rt.block_on(async move {
                let service = JointControlService {
                    shared: state_for_server,
                };

                let reflection_service = tonic_reflection::server::Builder::configure()
                    .register_encoded_file_descriptor_set(proto::FILE_DESCRIPTOR_SET)
                    .build_v1()
                    .expect("Failed to build gRPC reflection service");

                let addr: std::net::SocketAddr = addr.parse().expect("Invalid gRPC server address");

                info!("gRPC server listening on {}", addr);

                tonic::transport::Server::builder()
                    .add_service(reflection_service)
                    .add_service(JointControlServer::new(service))
                    .serve(addr)
                    .await
                    .expect("gRPC server failed");
            });
        });

        app.add_systems(Update, (publish_joint_states, apply_grpc_commands));
    }
}
